#!/usr/bin/env bash
set -Eeuo pipefail
# shellcheck source=lib.sh
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)/lib.sh"

validate_common_config
redacted() { [[ -n "$1" ]] && printf '<set>' || printf '<unset>'; }
printf '%-32s %s\n' \
    ROOT_DIR "$ROOT_DIR" \
    LLAMA_CPP_REPO "$LLAMA_CPP_REPO" \
    LLAMA_CPP_REF "$LLAMA_CPP_REF" \
    SOURCE_DIR "$SOURCE_DIR_ABS" \
    BUILD_DIR "$BUILD_DIR_ABS" \
    OUTPUT_DIR "$OUTPUT_DIR_ABS" \
    MODEL_DIR "$MODEL_DIR_ABS" \
    CMAKE_GENERATOR "$(choose_generator)" \
    BUILD_JOBS "$(build_jobs)" \
    BUILD_TARGETS "$BUILD_TARGETS" \
    CMAKE_C_COMPILER "$(selected_cc)" \
    CMAKE_CXX_COMPILER "$(selected_cxx)" \
    C_FLAGS_RELEASE "$(effective_c_flags)" \
    CXX_FLAGS_RELEASE "$(effective_cxx_flags)" \
    GGML_NATIVE "$GGML_NATIVE" \
    ENABLE_LTO "$ENABLE_LTO" \
    ENABLE_CCACHE "$ENABLE_CCACHE" \
    ENABLE_OPENMP "$ENABLE_OPENMP" \
    ENABLE_CPU_REPACK "$ENABLE_CPU_REPACK" \
    ENABLE_LLAMAFILE "$ENABLE_LLAMAFILE" \
    ENABLE_FAST_MATH "$ENABLE_FAST_MATH" \
    ENABLE_BLAS "$ENABLE_BLAS" \
    BLAS_VENDOR "$BLAS_VENDOR" \
    ENABLE_CUDA "$ENABLE_CUDA" \
    CUDA_ARCHS "$CUDA_ARCHS" \
    ENABLE_HIP "$ENABLE_HIP" \
    AMDGPU_TARGETS "$AMDGPU_TARGETS" \
    ENABLE_VULKAN "$ENABLE_VULKAN" \
    ENABLE_SYCL "$ENABLE_SYCL" \
    SYCL_TARGET "$SYCL_TARGET" \
    ENABLE_OPENCL "$ENABLE_OPENCL" \
    ENABLE_OPENVINO "$ENABLE_OPENVINO" \
    ENABLE_RPC "$ENABLE_RPC" \
    ENABLE_SERVER_UI "$ENABLE_SERVER_UI" \
    ENABLE_OPENSSL "$ENABLE_OPENSSL" \
    OFFLINE "$OFFLINE" \
    MODEL "${MODEL:-<interactive-or-single-local-model>}" \
    HF_REPO "${HF_REPO:-<catalog>}" \
    HF_FILE "${HF_FILE:-<catalog-or-quant-resolution>}" \
    HF_QUANT "$HF_QUANT" \
    HF_REVISION "$HF_REVISION" \
    HF_TOKEN "$(redacted "$HF_TOKEN")" \
    DOWNLOAD_MMPROJ "$DOWNLOAD_MMPROJ" \
    VERIFY_REMOTE_SHA256 "$VERIFY_REMOTE_SHA256" \
    STRICT_CHECKSUM "$STRICT_CHECKSUM" \
    RUNTIME_THREADS "$(resolve_threads "$RUNTIME_THREADS")" \
    RUNTIME_THREADS_BATCH "$(resolve_threads "$RUNTIME_THREADS_BATCH" logical)" \
    GPU_LAYERS "$GPU_LAYERS" \
    RUNTIME_DEVICE "${RUNTIME_DEVICE:-<auto>}" \
    CTX_SIZE "$CTX_SIZE" \
    ENABLE_USER_SERVICE "$ENABLE_USER_SERVICE" \
    SERVICE_NAME "$SERVICE_NAME" \
    SERVER_MODEL "$SERVER_MODEL" \
    SERVER_MODEL_PATH "${SERVER_MODEL_PATH:-<local-id-resolution>}" \
    SERVER_ALIAS "$SERVER_ALIAS" \
    SERVER_HOST "$SERVER_HOST" \
    SERVER_PORT "$SERVER_PORT" \
    SERVER_THREADS "$(resolve_threads "$SERVER_THREADS")" \
    SERVER_THREADS_BATCH "$(resolve_threads "$SERVER_THREADS_BATCH" logical)" \
    SERVER_CTX_SIZE "$SERVER_CTX_SIZE" \
    SERVER_PARALLEL "$SERVER_PARALLEL" \
    SERVER_GPU_LAYERS "$SERVER_GPU_LAYERS" \
    SERVER_DEVICE "${SERVER_DEVICE:-<auto>}" \
    SERVER_FLASH_ATTN "$SERVER_FLASH_ATTN" \
    SERVER_LOAD_MODE "$SERVER_LOAD_MODE" \
    SERVER_KEEP_MODEL_LOADED "$SERVER_KEEP_MODEL_LOADED" \
    SERVER_SLEEP_IDLE_SECONDS "$SERVER_SLEEP_IDLE_SECONDS" \
    SERVER_PIN_MODEL "$SERVER_PIN_MODEL" \
    SERVER_FULL_GPU_OFFLOAD "$SERVER_FULL_GPU_OFFLOAD" \
    SERVER_CACHE_TYPE_K "$SERVER_CACHE_TYPE_K" \
    SERVER_CACHE_TYPE_V "$SERVER_CACHE_TYPE_V" \
    SERVER_CONT_BATCHING "$SERVER_CONT_BATCHING" \
    SERVER_METRICS "$SERVER_METRICS" \
    SERVER_EMBEDDINGS "$SERVER_EMBEDDINGS" \
    SERVER_RERANKING "$SERVER_RERANKING" \
    SERVER_JINJA "$SERVER_JINJA" \
    SERVER_API_KEY "$(redacted "$SERVER_API_KEY")" \
    SERVER_TIMEOUT "$SERVER_TIMEOUT" \
    SERVER_EXTRA_ARGS "${SERVER_EXTRA_ARGS:-<none>}"
